const TelegramBot = require('node-telegram-bot-api');
const { approvePayment, getProject, updateProjectDeployment, updateProjectZipPath } = require('../database');
const { deployProject } = require('../services/deploy');
const fs = require('fs-extra');
require('dotenv').config();

const handlePaymentApproval = async (bot, callbackQuery) => {
  const data = callbackQuery.data;
  const message = callbackQuery.message;
  const adminId = callbackQuery.from.id;

  if (adminId.toString() !== process.env.ADMIN_CHAT_ID) {
    await bot.answerCallbackQuery(callbackQuery.id, { text: 'Unauthorized!' });
    return;
  }

  if (data.startsWith('approve_')) {
    const [_, paymentId, projectId] = data.split('_');
    
    try {
      await bot.answerCallbackQuery(callbackQuery.id, { text: 'Approving payment...' });
      
      // Approve payment
      await approvePayment(paymentId, projectId);
      
      // Get project details
      const project = await getProject(projectId);
      
      // Update message
      await bot.editMessageText(
        `✅ *Payment Approved*\n\nProject: ${project.project_name}\nStatus: Processing deployment...`,
        {
          chat_id: message.chat.id,
          message_id: message.message_id,
          parse_mode: 'Markdown'
        }
      );

      // Start deployment
      const deployment = await deployProject(
        projectId,
        project.user_id,
        project.project_name,
        project.description,
        project.project_type,
        project.domain_name
      );

      if (deployment.success) {
        // Update project with deployment info
        await updateProjectDeployment(
          projectId,
          deployment.githubUrl,
          deployment.netlifyUrl,
          'deployed'
        );

        if (deployment.zipPath) {
          await updateProjectZipPath(projectId, deployment.zipPath);
        }

        // Notify user
        await bot.sendMessage(project.user_id, `
✅ *Your project has been deployed successfully!*

📁 *Project:* ${project.project_name}
🌐 *Live URL:* ${deployment.netlifyUrl}
📦 *GitHub:* ${deployment.githubUrl}

Use /mybuilds to download your project ZIP file.
        `, { parse_mode: 'Markdown' });

        // Update admin message
        await bot.editMessageText(
          `✅ *Payment Approved & Deployed*\n\nProject: ${project.project_name}\nLive URL: ${deployment.netlifyUrl}`,
          {
            chat_id: message.chat.id,
            message_id: message.message_id,
            parse_mode: 'Markdown'
          }
        );

      } else {
        await updateProjectDeployment(projectId, null, null, 'failed');
        
        await bot.sendMessage(project.user_id, 
          '❌ Deployment failed. Our team will contact you shortly.',
          { parse_mode: 'Markdown' }
        );

        await bot.editMessageText(
          `⚠️ *Payment Approved but Deployment Failed*\n\nProject: ${project.project_name}\nError: ${deployment.error}`,
          {
            chat_id: message.chat.id,
            message_id: message.message_id,
            parse_mode: 'Markdown'
          }
        );
      }

    } catch (error) {
      console.error('Approval error:', error);
      await bot.editMessageText(
        `❌ *Error processing approval*\n\n${error.message}`,
        {
          chat_id: message.chat.id,
          message_id: message.message_id,
          parse_mode: 'Markdown'
        }
      );
    }

  } else if (data.startsWith('reject_')) {
    const [_, paymentId] = data.split('_');
    
    try {
      // Update payment status to rejected
      // You might want to add this function to database.js
      
      await bot.editMessageText(
        '❌ *Payment Rejected*\n\nThe payment has been rejected by admin.',
        {
          chat_id: message.chat.id,
          message_id: message.message_id,
          parse_mode: 'Markdown'
        }
      );

      await bot.answerCallbackQuery(callbackQuery.id, { text: 'Payment rejected' });
    } catch (error) {
      console.error('Rejection error:', error);
    }
  }
};

const handleDownload = async (bot, callbackQuery) => {
  const data = callbackQuery.data;
  const userId = callbackQuery.from.id;

  if (data.startsWith('download_')) {
    const projectId = data.split('_')[1];
    
    try {
      const project = await getProject(projectId);
      
      if (!project || project.user_id !== userId) {
        await bot.answerCallbackQuery(callbackQuery.id, { text: 'Project not found!' });
        return;
      }

      if (project.zip_file_path && await fs.pathExists(project.zip_file_path)) {
        // Send the ZIP file
        await bot.sendDocument(userId, project.zip_file_path, {
          caption: `📁 *${project.project_name}* - Project Files\n\nGenerated by ClickDev AI`,
          parse_mode: 'Markdown'
        });
        
        await bot.answerCallbackQuery(callbackQuery.id, { text: 'Downloading...' });
      } else {
        await bot.answerCallbackQuery(callbackQuery.id, { text: 'ZIP file not found!' });
      }

    } catch (error) {
      console.error('Download error:', error);
      await bot.answerCallbackQuery(callbackQuery.id, { text: 'Error downloading file!' });
    }
  }
};

module.exports = { handlePaymentApproval, handleDownload };
