const archiver = require('archiver');
const fs = require('fs-extra');
const path = require('path');
const { createGitHubRepo } = require('./github');
const { deployToNetlify, updateCustomDomain } = require('./netlify');
const { generateWebsiteCode } = require('./gemini');

const createProjectZip = async (projectId, files) => {
  return new Promise(async (resolve, reject) => {
    try {
      const zipPath = path.join(__dirname, '../../zips', `project_${projectId}.zip`);
      await fs.ensureDir(path.dirname(zipPath));
      
      const output = fs.createWriteStream(zipPath);
      const archive = archiver('zip', {
        zlib: { level: 9 }
      });

      output.on('close', () => {
        resolve(zipPath);
      });

      archive.on('error', (err) => {
        reject(err);
      });

      archive.pipe(output);

      // Add files to zip
      for (const [filename, content] of Object.entries(files)) {
        archive.append(content, { name: filename });
      }

      // Add README
      const readme = `# Project Generated by ClickDev AI\n\nThis project was created using ClickDev AI Telegram Bot.\n\nGenerated on: ${new Date().toISOString()}`;
      archive.append(readme, { name: 'README.md' });

      await archive.finalize();
    } catch (error) {
      reject(error);
    }
  });
};

const deployProject = async (projectId, userId, projectName, description, projectType, domain) => {
  try {
    // Generate code using Gemini
    const files = await generateWebsiteCode(description, projectType);
    
    // Create GitHub repository
    const repoName = `clickdev-${userId}-${projectId}`.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    const githubResult = await createGitHubRepo(repoName, files);
    
    if (!githubResult.success) {
      throw new Error('GitHub repo creation failed');
    }

    // Deploy to Netlify
    const siteName = `clickdev-${userId}-${projectId}`.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    const netlifyResult = await deployToNetlify(siteName, files);
    
    if (!netlifyResult.success) {
      throw new Error('Netlify deployment failed');
    }

    // Create ZIP file
    const zipPath = await createProjectZip(projectId, files);

    return {
      success: true,
      githubUrl: githubResult.url,
      netlifyUrl: netlifyResult.url,
      zipPath: zipPath,
      files: files
    };
  } catch (error) {
    console.error('Deployment error:', error);
    return {
      success: false,
      error: error.message
    };
  }
};

const updateProjectDomain = async (siteId, newDomain) => {
  return await updateCustomDomain(siteId, newDomain);
};

module.exports = { deployProject, updateProjectDomain };
